### ISSUE TITLE
TypeError: Cannot read property 'removeEventListener' of undefined when switching routes with toast

### ISSUE THREAD

**Issue by dylanmcgowan** [sweetalert2/sweetalert2#1320]
## Current behavior

I'm using a mixin for a global toast alert like this:

```
export const toast = swal.mixin({
  toast: true,
  position: 'bottom',
  showConfirmButton: false,
  timer: 5000,
  type: 'success',
})
```

If the toast is active when switching routes this div shows up and does not go away. (an opaque black overlay)
`body > div.swal2-container.swal2-bottom.swal2-fade.swal2-shown`

After the 5000ms timeout, this error gets thrown:
```
Uncaught TypeError: Cannot read property 'removeEventListener' of undefined
    at removePopupAndResetState (vendors.app.js:55341)
    at HTMLDivElement.swalCloseEventFinished (vendors.app.js:55369)
```

And undefined comes from the `removePopupAndResetState` function:

```
var removePopupAndResetState = function removePopupAndResetState() {
    if (!isToast()) {
      restoreActiveElement().then(function () {
        return triggerOnAfterClose(onAfterClose);
      });
      globalState.keydownTarget.removeEventListener('keydown', globalState.keydownHandler, {
        capture: globalState.keydownListenerCapture
      });
      globalState.keydownHandlerAdded = false;
    } else {
      triggerOnAfterClose(onAfterClose);
    }

    if (container.parentNode) {
      container.parentNode.removeChild(container);
    }
```

## Expected behavior

The toast should either get destroyed completely or time out correctly. Ideally it would time out, but destroying it all together would still be a better UX than refreshing the page because of a mask that never dissapears.

**Comment by limonte** [comment]
Thank you @dylanmcgowan for the detailed issue report!

I suspect the issue is somewhere here "when switching routes". Is it possible to provide a live demo of the router you're using?

**Comment by dolphinsd** [comment]
@limonte feel free to create test account at omnibasis.com - we are using your library and see the issue or route switch sometimes when popup appear after backend operation with success but routes are switched.

**Comment by dylanmcgowan** [comment]
Heres a video demo of the bug:
https://www.useloom.com/share/91a06d1bc35f4d56884c0d86800b3a55

Unfortunately I copied my configuration verbatim and can't reproduce the bug in a virtual environment.. but here's what that code looks like anyway:
https://codesandbox.io/s/jzqxqpw5lv

Also sorry for the late reply, been a very busy week.  I'm happy to do whatever I can to help solve this!

**Comment by gverni** [comment]
Hi @dylanmcgowan is the bug reproduced consistently (i.e. 100% of the time) on your development environment? 

> Unfortunately I copied my configuration verbatim and can't reproduce the bug in a virtual environment

Unfortunately I can confirm i cannot see the issue either.

**Comment by gverni** [comment]
Hi @dylanmcgowan I think I may have actually recreated your issue. Can you check if when you switch route you remove class `swal2-toast-shown` from the `body`? I tried to manually removed and i have a very similar behavior as the video you sent us (e.g. grey overlay + error in console). I'm not familiar with vue, but i'll give it a try to reproduce what I mean on your codesandbox. If i manage to, i'll update this issue.

**Comment by gverni** [comment]
Here you go: https://codesandbox.io/s/3kqpr9y12q. In this one I'm adding:

`document.querySelector('body').setAttribute('class', '')`

When switching to route `about`. You can see the grey overlay when the about page is rendered, and the error in console when the toast is closed (it took me 5 minutes to figure out that codesandbox doesn't show console errors in its console, and you have to open the browser dev tools)

**Comment by limonte** [comment]
Closing this as `wontfix`, you guys need to figure out why SweetAlert2's classes (`swal2-toast-shown swal2-shown`) are removed from body when changing routes. There should be some way to prevent router from removing those classes.

**Comment by davalapar** [comment]
Found a possible issue of this, one is nesting Swal onClose functions.

**Comment by limonte** [comment]
@davalapar thanks for reporting, fixed

**Comment by leo108** [comment]
I got this issue again when I upgrade from 8.13.1 to 8.13.4, no other code changes.

**Comment by gverni** [comment]
@leo108 we made some changes to the closing sequence in v8.13.2 and subsequent. Is it possible for you to update to v8.14.0 and try again if you still see the issue? If you do, it would be good if you can provide some more info on how you reproduce that. There are a couple of different issues on this ticket, and it would be good to understand which one you are having.

**Comment by limonte** [comment]
@gverni FYI I removed `no-response` bot, its recente activity doesn't make much sense to me.

**Comment by gverni** [comment]
@limonte, it actually works as expected, even though it's a weird design choice. If you look at their README, it says that it closes the issue if: 

* The `responseRequiredLabel` was applied more than `daysUntilClose` ago

In this case the label was applied long time ago, and hence it closes the ticket. I had to remove the label and put it back to stop it. I was thinking to open a feature request to `no-response` to ask to use the last comment date instead of the label application date.

**Comment by leo108** [comment]
@gverni Yes, v8.14.0 fixes the issue, thanks.

**Comment by limonte** [comment]
thank you for your feedback @leo108 I'm closing the issue :+1:

**Comment by Ajinkyadon** [comment]
This issue raised when i add

document.body.className = 'hold-transition sidebar-mini layout-fixed layout-navbar-fixed';

**Comment by Ajinkyadon** [comment]
@gverni  i fixed this issue by adding 

 document.body.className = 'hold-transition sidebar-mini layout-fixed layout-navbar-fixed swal2-toast-shown swal2-shown'; 

**swal2-toast-shown swal2-shown**

**Comment by Ajinkyadon** [comment]
@franklinpious  you need to debug ,..
Check <body> tag class 
swal2-toast-shown swal2-shown';
Add this class to <body class="swal2-toast-shown swal2-shown" >


I hope it will help you.

**Comment by metacoding** [comment]
I still get this error in my react app. I am using sweetalert2 version 9.10.12

**Comment by dkaczor97** [comment]
@franklinpious I am facing the same issue. Have you somehow managed to fix it?

**Comment by qburst-franklin** [comment]
@dkaczor97 Sadly no.. I have currently disabled preloading. let me know if you get any fixes.

**Comment by franklinpious** [comment]
@dkaczor97 Unfortunately no.. I have currently disabled preloading. let me know if you get any fixes.

**Comment by franklinpious** [comment]
@dkaczor97 have you tried contacting the ASP.NET ZERO support ?

**Comment by dkaczor97** [comment]
@franklinpious no, I didn't

**Comment by Sniipe** [comment]
@franklinpious I am facing the same issue.  I have contacted ASP.NET ZERO support.  Awaiting reply: https://support.aspnetzero.com/QA/Questions/9245/abpnotify-feature

**Comment by franklinpious** [comment]
@Sniipe Did you face the issue after enabling preload in Angular?

**Comment by Sniipe** [comment]
hi @franklinpious 

- There is no import of "PreloadAllModules" anywhere in the solution.
- Nor is there an import of "PreloadingStrategy" anywhere in the solution.
- root-routing.module.ts has "data: { preload: true }" however this has been the case for the last year with no issue on this high traffic toast.
The same holds true for app-routing.module.ts.

**Comment by saadabdurrazaq** [comment]
I am using this way to solve this issue
`if(swal.isVisible()){
      document.querySelector('body').setAttribute('class', 'swal2-toast-shown swal2-shown')
    }`
