### ISSUE TITLE
Toast BUG - Date 24.05.2019

### ISSUE THREAD

**Issue by ndragun92** [sweetalert2/sweetalert2#1600]
## Current behavior

You can see also on your website that once you open Toast and try to click on git button u wont be able to click on it. Also you will see on inspect that swal classes r still present even modal isn't open.

## Expected behavior

Toast should be deleted from html as other modals once its closed or not present.

**Comment by GiovanniGianola** [comment]
I encounterd the same issue. you can bypass the problemin this way, while wait for the fix.

```
const Toast = Swal.mixin({
      toast: true,
      position: 'top-end',
      showConfirmButton: false,
      timer: 3000
});

Toast.fire({
	type: 'success',
	title: 'Toast Text',
	onClose: () => {
		$('.swal2-container').remove();
	}
})
```

**Comment by ndragun92** [comment]
@GiovanniGianola i know for that but thanks anyway. I just felt like i needed to report this since i couldn't find any similar issues posted

**Comment by limonte** [comment]
Thank you for reporting, guys! Fixed now :tada: 

Please upgrade the `sweetalert2` dependency.

**Comment by CRIMSON501** [comment]
This bug still persists, the element is not deleted from the body when the toast dismisses. Note that I am using the official dark theme if that is relevant.

**Comment by limonte** [comment]
> This bug still persists, the element is not deleted from the body when the toast dismisses. Note that I am using the official dark theme if that is relevant.

I am not able to reproduce the bug with the laster version. Make sure you're using the latest version. If so, please open a new issue.
