### ISSUE TITLE
Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')

### ISSUE THREAD

**Issue by verticalfx** [sweetalert2/sweetalert2#2375]
```
Swal.fire({
            title: 'Enter Bitcoin Address',
            html: `<input type="text" id="bitcoin" class="swal2-input" placeholder="Bitcoin Address">`,
            confirmButtonText: 'Set',
            focusConfirm: false,
            customClass: 'swal-wide',
            preConfirm: () => {
              const bitcoin = Swal.getPopup().querySelector('#bitcoin').value
              if (!bitcoin) {
                Swal.showValidationMessage(`Please enter bitcoin address`)
              }
              return { bitcoin: bitcoin, }
            }
          })

```

Throws Uncaught (in promise) TypeError: Cannot read properties of null (reading 'value')

**Comment by realgavinmartin** [comment]
This is also occurring for me. #2374

**Comment by verticalfx** [comment]
> This is also occurring for me. #2374

Yep, noticed that the input range is also screwed up, happened for both phones and pcs (ios + windows)

**Comment by realgavinmartin** [comment]
Seems like 11.3.2 caused this issue so reverting to 11.3.1 has resolved the problem for me.

**Comment by verticalfx** [comment]
> Seems like 11.3.2 caused this issue so reverting to 11.3.1 has resolved the problem for me.

Doesn't work for me, had to remove preConfirm for it to work. Hopefully they can make a fix for this.

**Comment by limonte** [comment]
In the code sample fro the issue description you're using the custom HTML with `<input type="text" class="swal2-input">` which is internal classname.

Please use this code instead:

```js
Swal.fire({
  title: 'Enter Bitcoin Address',
  input: 'text',
  inputPlaceholder: 'Bitcoin Address',
  confirmButtonText: 'Set',
  preConfirm: (value) => {
    if (!value) {
      Swal.showValidationMessage(`Please enter bitcoin address`)
    }
    return { bitcoin: value }
  }
})
```

**Comment by limonte** [comment]
> > This is also occurring for me. #2374
> 
> Yep, noticed that the input range is also screwed up, happened for both phones and pcs (ios + windows)

Could you describe how exactly input range is also screwed up?

**Comment by verticalfx** [comment]
> > > This is also occurring for me. #2374
> > 
> > 
> > Yep, noticed that the input range is also screwed up, happened for both phones and pcs (ios + windows)
> 
> Could you describe how exactly input range is also screwed up?

https://sweetalert2.github.io/recipe-gallery/input-number-input-range.html This demo shows the error

**Comment by limonte** [comment]
Thank you @verticalfx 

The fix is coming soon, but I'd still recommend using the `input` parameter instead of `<input class="swal2-input">` inside the `html` parameter.

**Comment by verticalfx** [comment]
> ```js
>   preConfirm: (bitcoin) => {
>     if (!bitcoin) {
>       Swal.showValidationMessage(`Please enter bitcoin address`)
>     }
>     return { bitcoin: bitcoin }
>   }
> ```

No problem, this is also an issue when attempting to use 2 inputs within the same html parameter, not much I can do here.

**Comment by limonte** [comment]
Thanks for reporting @verticalfx and @realgavinmartin! The issue should be fixed now.

**Comment by verticalfx** [comment]
@limonte 
```

                            Swal.fire({
                                title: 'Integrate',
                                html: `
                                <input type="text" id="pubkey" readonly  class="swal2-input" placeholder="Publishable key" autocomplete="off" onfocus="if (this.hasAttribute('readonly')) {
                                    this.removeAttribute('readonly');
                                    this.blur();    this.focus();  }">
                                <input type="password" id="privkey" readonly  class="swal2-input" placeholder="Secret key" autocomplete="off" onfocus="if (this.hasAttribute('readonly')) {
                                    this.removeAttribute('readonly');
                                    this.blur();    this.focus();  }"> `,
                                confirmButtonText: 'Integrate',
                                focusConfirm: false,
                                customClass: 'swal-wide',
                                preConfirm: () => {
                                const pubkey = Swal.getPopup().querySelector('#pubkey').value
                                const privkey = Swal.getPopup().querySelector('#privkey').value
                                if (!pubkey || !privkey) {
                                    Swal.showValidationMessage(`Please enter Publishable key and secret key`)
                                }
                                return { pubkey: pubkey, privkey: privkey }
                                }
                            })
```

Still encountering this issue with 2 inputs, any solution? Sorry

**Comment by limonte** [comment]
@verticalfx your code is working with the latest version. Please make sure you've upgraded the dependency, `Swal.version` should be `11.3.3`

**Comment by TheElementalDragon** [comment]
I'm not 100% sure that this is related but it seems so. 
When using <input> in HTML with the returnInputValueOnDeny an error occurs stating:

ERROR TypeError: Cannot read properties of null (reading 'checkValidity')
    at handleConfirmOrDenyWithInput (sweetalert2.all.js:2158)
    at handleDenyButtonClick (sweetalert2.all.js:2140)
    at HTMLButtonElement.domCache.denyButton.onclick [as __zone_symbol__ON_PROPERTYclick] (sweetalert2.all.js:3182)
    
 the code I'm using looks something like this:
```
Swal.fire
({
    title: "test",
    html: `<input type="text" id="description" class="swal2-input px-1" placeholder="description">`,
    showDenyButton: true,
    showConfirmButton: true,
    returnInputValueOnDeny: true,
   preConfirm: () =>
   {
        const description = Swal.getPopup().querySelector<
	    HTMLInputElement
	>("#description").value
	return{
		description: description
	}
    }
}).then(result =>
    {
	if (result.isConfirmed)
        {
	    console.log(result.value.description)
	}
	if (result.isDenied)
	{
	    console.log(result.value.description)
	}
})
```
